allowBuilds:
  electron: false
  electron-winstaller: false
  esbuild: false
onlyBuiltDependencies:
  - electron
  - esbuild
overrides:
  'vite': 'npm:@voidzero-dev/vite-plus-core@latest'
  'vitest': 'npm:@voidzero-dev/vite-plus-test@latest'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    'vite': '*'
    'vitest': '*'
